### ISSUE TITLE
Problems accessing for first time

### ISSUE THREAD

**Issue by fragtion** [techgarage-ir/MTWireGuard#1]
I get error in log "      Failed to determine the https port for redirect."

Web error:
500
Error connecting to the router api!
Login failed, The SSL connection could not be established, see inner exception.

**Comment by techgarage-ir** [comment]
The first error that appeared in logs belongs to panel's SSL support which is in process to solve and doesn't matters.

Getting error "500, connection could not be established" means you have misconfigured www-ssl service or certificate in RouterOS. Please provide information (with screenshot) about your www-ssl service and certificates to help solving problem.
