### ISSUE TITLE
[Fixed] عدم نمایش ترافیک یوزر

### ISSUE THREAD

**Issue by aliamg1356** [techgarage-ir/MTWireGuard#3]
با سلام
روی میکروتیک نصب شده اما ترافیک مصرفی کاربر رو نشون نمیده  فکر کنم اسکریپت درست عمل نمیکنه
در ضمن در قسمت تنظیمات بعضی گزینه ها غیر فعاله برای بنده
سپاس

**Comment by techgarage-ir** [comment]
با سلام
این مورد درحال بررسی میباشد.
